### PR TITLE
 Correct WIF byte marker for DARK addresses

### PR DESCRIPTION
**Pull request by ciband**
Updated devnet WIF byte marker to match Ark Core.

### CODE REVIEW

**Comment by ciband** [comment]
Working on fixing tests.  It appears some tests will need to be updated with the corrected expected values to match the updated WIF byte.

**Comment by faustbrian** [comment]
PRs for arkjs should now go to https://github.com/ArkEcosystem/core/tree/master/packages/crypto

**Comment by ciband** [comment]
Ah, my apologies.  I thought just ark-node was being deprecated in favor of ark-core.  I assume ark-js is going away as well?  Thank you.

**Comment by faustbrian** [comment]
Yeah, it will be deprecated soon too. It will keep existing for some time but any changes or additions should go to above link.

**Comment by ciband** [comment]
Closing since ark-core replaces ark-js and this issue has been fixed in ark-core.

**Pull request closed without merging**
