### PR TITLE
Fix missing dependency - create-hash

### PR DESCRIPTION
**Pull request by kost**
module.js:340
    throw err;
          ^
Error: Cannot find module 'create-hash'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/arkjs/lib/crypto.js:1:80)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

$ sudo npm install -g create-hash
create-hash@1.1.3 /usr/lib/node_modules/create-hash
├── inherits@2.0.3
├── sha.js@2.4.8
├── ripemd160@2.0.1 (hash-base@2.0.2)
└── cipher-base@1.0.4 (safe-buffer@5.1.1)

### CODE REVIEW

**Comment by luciorubeens** [comment]
thanks! +5

**Comment by boldninja** [comment]
@kost can you give me your ARK address for bounty?

**Comment by Isabello** [comment]
i sent this same pull request months ago and it wasn't merged. what gives?

**Comment by boldninja** [comment]
@Isabello Looking back at the PRs looks like you closed it before it could be merged? Can you also give me an ARK address and I'll send bounty to you as well.

**Comment by Isabello** [comment]
@boldninja it was open from feb22nd to july ;)

AcWYGwgCLU9D2JCT3TSxxEP8HPQ5sUsmi8

**Comment by kost** [comment]
@boldninja my ark address is: AKqPoqD3TzupxQjMskQY2oLWqi3aQvpXCq

Thanks in advance!

**Pull request merged**
