### PR TITLE
Add Visual Studio Code integration

### PR DESCRIPTION
**Pull request by dpyro**
- Recommended extensions
- Lint task
- Mocha debug
- Editor settings

### CODE REVIEW

**Comment by luciorubeens** [comment]
+5 👍🏻

**Comment by boldninja** [comment]
@dpyro can you give me ARK address for bounty distribution?

**Comment by dpyro** [comment]
@boldninja AUKoLR7UCjVrQEmbK5AD7eedK6Mz4rxC47

**Comment by boldninja** [comment]
@dpyro sent ;) keep up the good work.

**Pull request merged**
